---
- name: Install Kubernetes on cluster
  hosts: cluster
  become: yes
  strategy: linear
  serial:
    - 1
    - "50%"
    - "100%"
  remote_user: root
  vars_files:
    - vars/server.yaml
    - vars/join-secrets.yml
  roles:
    - kwoodson.yedit
  tasks:
    - name: Initiate Tasks
      include_tasks:
        file: jobs/run/common.yaml
      tags:
        - always