---
- name: Install Kubernetes on cluster
  hosts: cluster
  become: yes
  strategy: linear
  serial:
    - 1
    - "50%"
    - "100%"
  remote_user: root
  vars_files:
    - vars/server.yaml
    - vars/join-secrets.yml
  tasks:
    - name: Install K3s
      include_tasks:
        file: "{{ playbook_dir }}/jobs/common.yaml"
      tags:
        - always
