---
- name: Install Rancher Cluster Main Node
  hosts: cluster
  become: yes
  remote_user: root
  vars_files:
    - vars/server.yaml
  tasks:
    - name: Update and get container to standard point
      include_tasks: 
        file: jobs/initialize.yaml
        apply:
          tags:
            - enviro
    - name: Install K3s
      include_tasks: 
        file: jobs/install/k3s.yaml
        apply:
          tags:
            - enviro
      when: cluster.build == "k3s"
    - name: Install Kube Utils
      include_tasks: 
        file: jobs/install/kubeutils.yaml
        apply:
          tags:
            - enviro
    - name: Install k8s
      include_tasks: 
        file: jobs/install/k8s.yaml
        apply:
          tags:
            - k8s
      when: cluster.build == "k8s"
      
    - name: Configure Kubectl
      include_tasks: 
        file: jobs/configure/kubectl.yaml
        apply:
          tags:
            - k8s
            - k3s
            - kctl
    - name: Test Kubernetess
      include_tasks: 
        file: jobs/tests/kubernetes.yaml
        apply:
          tags:
            - k8s
            - k3s
            - test
    - name: Install Helm
      include_tasks: 
        file: jobs/install/helm.yaml
        apply:
          tags:
            - helm
            - rancher
            - cert-manager
    - name: Install Cert Manager
      include_tasks: 
        file: jobs/install/cert-manager.yaml
        apply:
          tags:
            - cert-manager
    - name: Test Cert Manager
      include_tasks: 
        file: jobs/tests/cert-manager.yaml
        apply:
          tags:
            - cert-manager
            - test
    - name: Install Rancher
      include_tasks: 
        file: jobs/install/rancher.yaml
        apply:
          tags:
            - rancher
    - name: Test Rancher
      include_tasks: 
        file: jobs/tests/rancher.yaml
        apply:
          tags:
            - rancher
            - test
