---
- name: Install Rancher Cluster Main Node
  hosts: cluster
  become: yes
  remote_user: root
  vars_files:
    - vars/server.yaml
  tasks:
    - name: Update and get container to standard point
      include_tasks: jobs/initialize.yaml
    - name: Install K3s
      include_tasks: jobs/install/k3s.yaml
    - name: Install Helm
      include_tasks: jobs/install/helm.yaml
    - name: Install Kubectl
      include_tasks: jobs/install/kubectl.yaml
    - name: Configure Kubectl
      include_tasks: jobs/configure/kubectl.yaml
    - name: Test K3s
      include_tasks: jobs/tests/k3s.yaml
    #- name: Install Cert Manager
    #  include_tasks: jobs/install/cert-manager.yaml
    #- name: Test Cert Manager
    #  include_tasks: jobs/tests/cert-manager.yaml
    - name: Install Rancher
      include_tasks: jobs/install/rancher.yaml
    - name: Test Rancher
      include_tasks: jobs/tests/rancher.yaml
