---
- name: Install Rancher Cluster Main Node
  hosts: cluster
  become: yes
  remote_user: root
  vars_files:
    - vars/server.yaml
  tasks:
    - name: Update and get container to standard point
      include_tasks: jobs/initialize.yaml
    - name: Install K3s
      include_tasks: jobs/install/k3s.yaml
      when: cluster.build == "k3s"
    - name: Install Kubectl
      include_tasks: jobs/install/kubectl.yaml
    - name: Configure Kubectl
      include_tasks: jobs/configure/kubectl.yaml
    - name: Install k8s
      include_tasks: jobs/install/k8s.yaml
      when: cluster.build == "k8s"
    - name: Test Kubernetess
      include_tasks: jobs/tests/kubernetes.yaml
    - name: Install Helm
      include_tasks: jobs/install/helm.yaml
    - name: Install Cert Manager
      include_tasks: jobs/install/cert-manager.yaml
      tags:
        - cert-manager
    - name: Test Cert Manager
      include_tasks: jobs/tests/cert-manager.yaml
      tags:
        - cert-manager
    - name: Install Rancher
      include_tasks: jobs/install/rancher.yaml
      tags:
        - rancher
    - name: Test Rancher
      include_tasks: jobs/tests/rancher.yaml
      tags:
        - rancher
