---
- name: Install Kubernetes on cluster
  hosts: cluster
  become: yes
  strategy: linear
  gather_facts: False
  serial:
    - 1
    - "100%"
  remote_user: root
  roles:
    - kwoodson.yedit
  vars_files:
    - vars/server.yaml
  vars_prompt:
    - name: k8stoken
      prompt: "What is the Join Token? (leave blank on first run)"
    - name: k8shash
      prompt: "What is the Join Hash? (leave blank on first run)"
  tasks:
    - name: Add cluster local dns info
      ansible.builtin.lineinfile:
        path: /etc/hosts.yaml
        line: "{{ cluster.ip }}  {{ cluster.fqdn }}"
        create: yes
    - name: Install K3s
      include_tasks: 
        file: jobs/install/k3s.yaml
        apply:
          tags:
            - k3s
            - initial
      tags:
        - k3s
        - initial
      when: cluster.build == "k3s"
    - name: Install Kube Utils
      include_tasks: 
        file: jobs/install/kubeutils.yaml
        apply:
          tags:
            - enviro
      tags:
        - enviro
    - name: reset kubeadm
      block:
        - name: Reset kubeadm
          shell: kubeadm reset
          ignore_errors: yes
        - name: Delete paths
          file:
            state: absent
            path: " {{ item }}"
          loop:
            - /etc/kubernetes/
            - /var/lib/kubelet/
            - /var/lib/etcd
      tags: resetkube, never
    - name: Install k8s
      include_tasks: 
        file: jobs/install/k8s.yaml
        apply:
          tags:
            - k8s
            - initial
      when: cluster.build == "k8s"
      tags:
        - k8s
        - initial
    - name: Configure Kubectl
      include_tasks: 
        file: jobs/configure/kubectl.yaml
        apply:
          tags:
            - k8s
            - k3s
            - kctl
      tags:
        - k8s
        - k3s
        - kctl
    - name: Install CNI
      include_tasks:
        file: jobs/install/canal.yaml
        apply:
          tags:
            - k8s
      tags:
        - k8s
    - name: Test Kubernetess
      include_tasks: 
        file: jobs/tests/kubernetes.yaml
        apply:
          tags:
            - k8s
            - k3s
            - test
      tags:
        - k8s
        - k3s
        - test
    - name: Install Helm
      include_tasks: 
        file: jobs/install/helm.yaml
        apply:
          tags:
            - helm
      tags:
        - helm
