---
- name: Install Kubernetes on Primary Control Node
  hosts: localhost
  become: yes
  connection: local
  vars_files:
    - vars/base.yaml
  tasks:
    - name: Initiate Tasks
      include_tasks:
        file: jobs/run/common.yaml
      tags:
        - always
