---
all:
  hosts:
    localhost:
  children:
    cluster:
      hosts:
      children:
        control:
          vars:
            node:
              type: control
              primary: no
          hosts:
            localhost:
              ansible_connection: local
              ansible_python_interpreter: /usr/bin/env python3
              localip: 10.2.144.3/24
              node:
                primary: yes
            control2.penguinzmedia.group:
              localip: 10.2.144.4/24
            control3.penguinzmedia.group:
              localip: 10.2.144.5/24
        worker:
          vars:
            node:
              type: worker
              primary: no
          hosts:
            worker1.penguinzmedia.group:
              localip: 10.2.144.6/24
            worker2.penguinzmedia.group:
              localip: 10.2.144.7/24
            worker3.penguinzmedia.group:
              localip: 10.2.144.8/24
