---
all:
  hosts:
    localhost:
  children:
    cluster:
      hosts:
      children:
        control:
          vars:
            node:
              type: control
              primary: no
          hosts:
            localhost:
              ansible_connection: local
              ansible_python_interpreter: /usr/bin/env python3
              vars:
                node:
                  primary: yes
            control2.penguinzmedia.group:
              vars:
                localip: 10.2.144.4/24
                node:
                  type: control
                  primary: no
            control3.penguinzmedia.group:
              vars:
                localip: 10.2.144.5/24
                node:
                  type: control
                  primary: no
        worker:
          vars:
            node:
              type: worker
              primary: no
          hosts:
            worker1.penguinzmedia.group:
              vars:
                localip: 10.2.144.6/24
                node:
                  type: worker
                  primary: no
            worker2.penguinzmedia.group:
              vars:
                localip: 10.2.144.7/24
                node:
                  type: worker
                  primary: no
            worker3.penguinzmedia.group:
              vars:
                localip: 10.2.144.8/24
                node:
                  type: worker
                  primary: no