---
- name: Install key
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
- name: Install Source Repo
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
- name: Update System with new Repo
  apt:
    update_cache: yes
    name: "*"
    state: latest
- name: Install Helm
  apt:
    name: helm
    state: latest
- name: Add Rancher chart repo
  community.kubernetes.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
- name: Add Jetstack chart repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
